### Criar uma nova notificação
POST http://localhost:3000/notifications
Content-Type: application/json

{
    "recipientId": "8f6e5d4c-3b2a-1f0e-9d8c-7b6a5f4e3d2c",
    "content": "Você recebeu uma nova mensagem!",
    "category": "message"
}

### Listar todas as notificações
GET http://localhost:3000/notifications

### Buscar uma notificação específica por ID
GET http://localhost:3000/notifications/1

### Atualizar uma notificação
PATCH http://localhost:3000/notifications/59ecf3de-0b05-4f5b-a37d-af952cd0467f/cancel
Content-Type: application/json

{
    "content": "Conteúdo atualizado da notificação",
    "category": "update"
}

### Deletar uma notificação

### Contar notificações de um destinatário
GET http://localhost:3000/notifications/count/from/8f6e5d4c-3b2a-1f0e-9d8c-7b6a5f4e3d2c

### Buscar notificações de um destinatário
GET http://localhost:3000/notifications/from/8f6e5d4c-3b2a-1f0e-9d8c-7b6a5f4e3d2c

### Marcar notificação como lida
PATCH http://localhost:3000/notifications/59ecf3de-0b05-4f5b-a37d-af952cd0467f/read

### Marcar notificação como não lida
PATCH http://localhost:3000/notifications/59ecf3de-0b05-4f5b-a37d-af952cd0467f/unread
