name: Deploy Notifications Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install   # sem working-directory

      - name: Build the application
        run: npm run build  # sem working-directory

      - name: Login to Docker Hub service
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin"

      - name: Build Docker image
        run: docker build -t nattanjr/notifications-service .

      - name: Push Docker image
        run: docker push nattanjr/notifications-service
