name: Pipeline Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: src
       
      - name: Backup and patch prisma schema for lambda
        run: | 
          cp prisma/schema.prisma prisma/schema.prisma.backup
          sed -i 's/binaryTargets = \[.*\]/binaryTargets = ["native" or "rhel-openssl-3.0.x"]/' prisma/schema.prisma
        working-directory: src

      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: src

      - name: Restore original prisma schema
        run: mv prisma/schema.prisma.backup prisma/schema.prisma
        working-directory: src

      - name: Run tests
        run: npm run test
        working-directory: src

      - name: Build the application
        run: npm run build
        working-directory: src

      - name: Zip Lambda source and dependencies
        run: |
          cd src
          zip -r ../deployment.zip . -x "*.git*" "*.github*" "test/" "*.log" "*.md" "npm-debug.log" 
        working-directory: src

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: notifications-service
          zip_file: deployment.zip
        working-directory: src